### ISSUE TITLE
LineEdit doesn't open keyboard

### ISSUE THREAD

**Issue by AndusDEV** [SonicMastr/godot-vita#23]
**Godot version:** 3.5-rc5

**OS/device including version:** 

**Issue description:** When clicking on LineEdit the keyboard doesn't show up

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by SonicMastr** [comment]
You need to use Actions builds for OSK support. This will come to release in a later update

**Comment by SudhaRatan** [comment]
> You need to use Actions builds for OSK support. This will come to release in a later update

Hey can you please share the build.
Thanks
