### ISSUE TITLE
Incorrect delta value

### ISSUE THREAD

**Issue by securas** [SonicMastr/godot-vita#25]
The value of delta seems to always be that of 60 FPS, even if the game is running at 30 or 40 FPS (measured by checking the output of Engine.get_frames_per_second() )
This prevents minimally accurate motion.

**Comment by SonicMastr** [comment]
If you may, could you test the latest build in actions and confirm proper functionality? (should just require an Eboot swap)

**Comment by SonicMastr** [comment]
Confirmed fixed in ba77c5825a5d9628d62718fe7997432e50bbfb86

**Comment by securas** [comment]
Sorry... I was unable to test in time.
I'll recheck again this weekend but I'm confident it should be ok.

cheers,
Securas
