### ISSUE TITLE
video freezes

### ISSUE THREAD

**Issue by zenogears** [SonicMastr/godot-vita#27]
Godot version: 3.6
OS/device including version: Vita
Issue description: video playback freezes, plays like slideshow.
Steps to reproduce: add VideoPlayer, add stream  with video ogv (Codec: Xiph.org's Theora Video (theo), Video resolution: 640x480, encoder: Lavc58.134.100 libtheora)
Minimal reproduction project: 
[Project.tar.gz](https://mega.nz/file/HRxizbbL#wWkp0pRfHbglDVHp6TOP4z9GrJy75UVHJjiuPJvrnBs)
[Vita.vpk](https://mega.nz/file/eRxkxZSB#evnjxa4nJXvHepS4ydb7fsEYbQ4Uo1akHwT8_XTXa1E)

Maybe there is some hacks for vita video playback without freezes?
Thanks!

**Comment by PSVita-Dev** [comment]
I'd like to add that I also have this issue, but it might be a problem with the engine and not the port, webm files also play like a slideshow on android while ogv is OK.

**Comment by SonicMastr** [comment]
Vita only supports hardware H264 decoding, which is not implemented. All other formats will use CPU decoding. libtheora playback will slow down and try to catch up if it can't decode fast enough.
