### ISSUE TITLE
any way to port it to godot 4?

### ISSUE THREAD

**Issue by Lewis-glasgow** [SonicMastr/godot-vita#28]
**IMPORTANT, PLEASE READ**

Feature / Enhancement requests are no longer accepted in the main Godot repository.
Please open an item by filling the relevant fields in the *Proposals* repository:

https://github.com/godotengine/godot-proposals/issues/new/choose

Do not submit to this repository or your issue will be closed.

**IMPORTANT, PLEASE READ**

**Comment by PSVita-Dev** [comment]
Theoretically, yes Godot 4 does not have an opengl es 2 driver currently, so no "quick" way. The other way would be writing a vita or gles2 driver (That takes a long time to get 2d and 3d rendering working)
