### ISSUE TITLE
Please update files

### ISSUE THREAD

**Issue by Dima353** [SonicMastr/godot-vita#29]
Artifacts are outdated, please update.
           
 You can get the Vita Template here: https://github.com/SonicMastr/godot-vita/actions/runs/4623774966
And the Windows build of the Godot editor here: https://github.com/SonicMastr/godot-vita/actions/runs/4623774984
Linux: https://github.com/SonicMastr/godot-vita/actions/runs/4623774963
OSX: https://github.com/SonicMastr/godot-vita/actions/runs/4623774964

Remember, this is 3.6 beta

_Originally posted by @SonicMastr in https://github.com/SonicMastr/godot-vita/issues/26#issuecomment-1504060182_

**Comment by astearon** [comment]
Artifacts are outdated, please update.
