### ISSUE TITLE
Game quits on startup

### ISSUE THREAD

**Issue by Red1C3** [SonicMastr/godot-vita#33]
**Godot version:**
3.5-rc5 Linux Release

**OS/device including version:**
PSV-1000 On 3.65 Henkaku

**Issue description:**
Game builds successfully, VPK installs successfully, but when I try to run the executable on the PSV, it quits as if I pressed the PS button, it doesn't crash, just quits gracefully, I've tried adjusting window settings, no difference, note that I'm exporting "without debug" if that matters.

**Steps to reproduce:**
Build and run.

**Minimal reproduction project:**
https://github.com/Red1C3/antware-godot-edition/tree/psvita

**Comment by PSVita-Dev** [comment]
You might want to include the Vita's stdio in that case

**Comment by Red1C3** [comment]
I ran PrincessLog, the logs said I must turn on GLES2 fallback option, altho I had the build on GLES2 beforehand, anyway it boots now, at least the main menu does
