### ISSUE TITLE
param.sfo on macOS error

### ISSUE THREAD

**Issue by pryces** [SonicMastr/godot-vita#42]
**Godot version:**
3.5rc2
**OS/device including version:**
M1 MacBook Air macOS Sonoma 14.1.2
**Issue description:**
Exporting to vita produces an invalid param.sfo on macOS. Unable to boot the game after installing the vpk

**Comment by SonicMastr** [comment]
This is a duplicate issue, but it has been fixed for a while. The updated versions are in the Actions builds
