### ISSUE TITLE
VitaShell Errors

### ISSUE THREAD

**Issue by 4stacks67** [SonicMastr/godot-vita#43]
**Godot version:**
3.5
**OS/device including version:**
Windows 11
**Issue description:**
Every time I Export It And Add it Into VitaShell It Gives Me AN Error
**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by 4stacks67** [comment]
There's no comments as i'm typing this

**Comment by PublicVoidUpdate** [comment]
is this with all projects or just one?


(i am not a maintainer, but i want to help this project)

**Comment by 4stacks67** [comment]
I'm Glad You Asked! All Projects

**Comment by 4stacks67** [comment]
No i don't

**Comment by PublicVoidUpdate** [comment]
damn. if you send me a minimal project i could see if its an os issue.

**Comment by PublicVoidUpdate** [comment]
i have a linux machine with this godot installed.

**Comment by 4stacks67** [comment]
Can u send me it

**Comment by 4stacks67** [comment]
I still can't fix the problem, can someone please help
