### ISSUE TITLE
0x8010113D 

### ISSUE THREAD

**Issue by StaringJokr** [SonicMastr/godot-vita#49]
**Godot version:**
Godot_v3.5-rc5-vita
**OS/device including version:**
win10/PSVita3.74  _**(Maybe I need to change the firmware to 3.60?)**_
**Issue description:**
I created a project that had only a text field. But I still get the error 0x8010113D

**Steps to reproduce:**
😐I created a project that had only a text field. But I still get the error 0x8010113D
**Minimal reproduction project:**
![1](https://github.com/SonicMastr/godot-vita/assets/103019103/ed780c11-8bda-4dd7-8d0a-6455e0c56637)
![2](https://github.com/SonicMastr/godot-vita/assets/103019103/33710bee-e463-4ffd-bc69-9787ae2e9054)
![2024-05-01-131621](https://github.com/SonicMastr/godot-vita/assets/103019103/62e3c6bd-f867-4db4-919e-f58949c2d813)

**Comment by StaringJokr** [comment]
I changed the version to 3.65, but it didn't help😥

**Comment by ZFhuang** [comment]
This is a problem of not setting the sys image correctly. You can refer to this issue: https://github.com/SonicMastr/godot-vita/issues/8
