### ISSUE TITLE
error 0x80101104 

### ISSUE THREAD

**Issue by thatoneham** [SonicMastr/godot-vita#55]
**Godot version:**
Godot_v3.5-rc5-vita
**OS/device including version:**
windows 11
**Issue description:**
i had issues with error 0x8010113d. after fixing im getting error 0x80101104 in vita shell
**Steps to reproduce:**
package a project with i think a invalid png
**Minimal reproduction project:**
https://drive.google.com/file/d/1FfEVTLs4tkZkI0wj_3qVEo677STLt1YU/view?usp=sharing

**Comment by thatoneham** [comment]
i have godot 3.6 beta but for some reason it doesnt want to install the tpz at all. or any tpzs

**Comment by thatoneham** [comment]
fixed myself

**Comment by SudhaRatan** [comment]
Hey I'm facing the same issue, can you please tell me how you resolved
