### ISSUE TITLE
error 0x8010113D but weird godot bug aswell

### ISSUE THREAD

**Issue by thatoneham** [SonicMastr/godot-vita#57]
**Godot version:**
3.6.beta
**OS/device including version:**
windows 11
**Issue description:**
error 0x8010113D
**Steps to reproduce:**
apparently its because of a wrong splash image. that wasnt run through pnquant but no matter how much times i restart and get a new project it keeps popping up. ive tried starting from 0 and reimporting the project when it wasnt modified. 
**Minimal reproduction project:**
im tryna port this project which was made in godot 3.6
https://drive.google.com/file/d/1iy8viik_Cns2hEc_pNfkeW4QjvmUYX6i/view?usp=sharing
there are a couple vpks in there from my failed attempts.

**Comment by thatoneham** [comment]
also when i tried to import a project that *i know* worked before from 3.5 into 3.6 the splash screen from the project above also is used? i saw that it has the same splash and all in vita3k which i used to test the splashes

**Comment by thatoneham** [comment]
and it gave me the same bug

**Comment by thatoneham** [comment]
fixed myself

**Comment by stand777free-beep** [comment]
Hi, I saw your comment. It's very interesting. How do you make games on Godot 3.6 for PS Vita?
